### ISSUE TITLE
Could we get our own Travis CI to cut down the build time?

### ISSUE THREAD

**Issue by acbegen** [Dash-Industry-Forum/Dash-Industry-Forum.github.io#37]
This would really make me happy

**Comment by wilaw** [comment]
What do we need to host this? DASH IF has 3 Amazon instances that we use for testvectors, reference client and livesim. We could run a build system on the reference client instance as it is lightly loaded. I don't know what to install and how to link it, but I can give access credentials to the EC2 instance for someone who does?

**Comment by acbegen** [comment]
@edrthomas ?

**Comment by edrthomas** [comment]
GitHub now offers a build system integrated.

If we migrate from Travis to Github for building the website, I expect this would cut down some delay.

Also, this would be better for the website maintenant since everything would be centralized on GitHub, no more 3rd party service involved.

Should we try this and see if building time gets better?

**Comment by wilaw** [comment]
Yes!

**Comment by edrthomas** [comment]
@wilaw @acbegen I have switched to GitHub Actions for building and publishing the website. Let me know if you see any issue in the coming days.

From my quick experiments with GitHub own CI, the website builds in about a minute. But note that I am not using caching in the build , we could save few seconds there. What seems better compared to Travis CI is the boot time.

I am curious to hear from your feedback.

**Comment by wilaw** [comment]
Thanks Emmanuel for all this work!  It’s a nice upgrade to have the build local to github. I’ll let you know if I notice any errors in the next few weeks.

Cheers
Will
